source 'https://github.com/CocoaPods/Specs.git'  # 官方库

target 'BaseProject' do
	pod ‘AFNetworking’
	pod ‘ReactiveObjC’
	pod ’DZNEmptyDataSet’
	pod ‘Masonry’
	pod ‘SVProgressHUD’
	pod ‘IQKeyboardManager’
	pod ‘YYModel’
	pod ‘KMNavigationBarTransition’
end
